### ISSUE TITLE
supports 'invalid configuration'

### ISSUE THREAD

**Issue by Dreamsorcerer** [PSPDFKit-labs/browserslist.dev#13]
The site shows 'invalid configuration' when using the 'supports es6-module' example from https://github.com/browserslist/browserslist#readme

**Comment by Dreamsorcerer** [comment]
Ah, I think it's because the site is using 4.13, looks like the feature is newer.

**Comment by ritz078** [comment]
This feature isn't available in the client-side version of browserslist that we use. I will have a look into this.

Thanks for reporting the issue.
