### ISSUE TITLE
Outdated data?

### ISSUE THREAD

**Issue by vaxul** [PSPDFKit-labs/browserslist.dev#25]
Hi, thank you for this nice tool.

Is the data for the queries outdated? A query for 'last 2 major versions' shows Chrome v86/85. Current would be v90/89.

**Comment by leonsmith** [comment]
Might be worth re-deploying with the latest `caniuse-lite` dep?

**Comment by applemonkey496** [comment]
It might also be useful to bump the browserslist version. The new `supports` query doesn't seem to work.

**Comment by ritz078** [comment]
Both browserslist and caniuse data have been updated. Sorry for the delay on this one. We will keep a closer look at this going forward.
