### ISSUE TITLE
Better feedback on valid options

### ISSUE THREAD

**Issue by Dreamsorcerer** [PSPDFKit-labs/browserslist.dev#39]
When trying out the 'supports' feature, it seems that it if it fails to recognise a name, it gives no indication.

Expected behaviour would be an invalid configuration error, or atleast some kind of feedback that confirms what it is actually searching.

For example, I wanted to search for this intersection of features:
`supports custom-elementsv1 and supports es6-module-dynamic-import and supports es6-class and supports replace-all and supports shadowdomv1`

But, when pasting that in, nothing changes. If I remove half the string, then the coverage goes down, which is obviously impossible. It seems that one of the values is not recognised, but it's rather difficult to figure out which one.

**Comment by Dreamsorcerer** [comment]
In this case it appears to be the `replace-all`, as it looks like browserlist does not have all features available.

**Comment by ritz078** [comment]
I think the error should be handled by browserslist. right now browserslist isn't throwing a stable error for missing features.

**Comment by Dreamsorcerer** [comment]
@ritz078 They seem to think the error message is clear: https://github.com/browserslist/browserslist/issues/684#issuecomment-1094360792

**Comment by Dreamsorcerer** [comment]
Looks like there has been a new PR relating to this. So, maybe now you can use those errors?
https://github.com/browserslist/browserslist/pull/714
