### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by icecream17** [PSPDFKit-labs/browserslist.dev#50]
chrome 98, firefox 96, etc have been released, but aren't included

**Comment by jnfaerch** [comment]
The website is indeed outdated as it utilizes an old version of caniuse-db

![Screenshot-20220209111224-261x100](https://user-images.githubusercontent.com/32164538/153177293-7c3fa5a5-1252-4611-ab6d-61a49cf74910.png)

We are currently at version ...1310
