### ISSUE TITLE
defaults without Opera Mini

### ISSUE THREAD

**Issue by rctneil** [PSPDFKit-labs/browserslist.dev#62]
Hi,

Just tried a query of "defaults and not Opera Mini" but it errors.  Why is this?

**Comment by SinanBaymammadli** [comment]
try "defaults and not op_mini all"

**Comment by rctneil** [comment]
Thankyou.  How do I exclude Opera Mobile, UC Browser, and QQ Browser from this too?

**Comment by marek-saji** [comment]
@rctneil You can find identifiers for browsers in browserlist docs: https://github.com/browserslist/browserslist#browsers

**Comment by miguelcalderon** [comment]
Not an issue we can solve, closing.
