### ISSUE TITLE
404 feature not found

### ISSUE THREAD

**Issue by botoxparty** [PSPDFKit-labs/browserslist.dev#63]
Hi,

When testing my browserslist string I get a 404 error in the network request to `/browsers` with the message 'Feature not found'.

This is an example of the string i'm using: 
https://browserslist.dev/?q=PiAxJSBpbiBERSBvciBsYXN0IDIgeWVhcnMgYW5kIHN1cHBvcnRzIGFzeW5jLWZ1bmN0aW9ucw%3D%3D

`> 1% in DE or last 2 years and supports async-functions` 

I'm pretty sure this was previously working a month or so ago..

**Comment by LeonSolisPedro** [comment]
I'm having the same issue, its definitely a bug...

**Comment by assmith** [comment]
This happens whenever you use the keyword "in". e.g.

> 1% in AU
> 1% in US
etc
