### ISSUE TITLE
Does this support comma-separated lists?

### ISSUE THREAD

**Issue by AndersDJohnson** [PSPDFKit-labs/browserslist.dev#69]
This is an awesome tool!

We seem to notice it may not be supporting comma-separated lists properly.

E.g., https://browserslist.dev/?q=PiAwLjUlIGluIFVTLCBzYWZhcmkgPj0gMTEsIG5vdCBkZWFkLCBub3QgSUUgPiAw does not seem to include Safari 11.

Compare to other tools like https://browsersl.ist/#q=%3E+0.5%25+in+US%2C+safari+%3E%3D+11%2C+not+dead%2C+not+IE+%3E+0

I think if we can't support, we could at least validate input or message to be sure users aren't misled. Thoughts?

**Comment by miguelcalderon** [comment]
@AndersDJohnson it is supported: the query string is directly passed on to Browserslist, but for some reason sometimes it's returning stale data.
