### ISSUE TITLE
last 1 major versions is returning deprecated data

### ISSUE THREAD

**Issue by Th3S4mur41** [PSPDFKit-labs/browserslist.dev#72]
![image](https://user-images.githubusercontent.com/5543595/201712431-4dc046eb-bc3b-4e21-acf4-9a1b44d8ca8f.png)

Safari should be 16, Chrome and Edge 107, Firefox 106, ...

![image](https://user-images.githubusercontent.com/5543595/201712778-7f81d31c-60b9-4f51-aaf5-2ea914186ffb.png)

**Comment by ritz078** [comment]
This has been fixed. Thank you.
